# -*- mode: python -*-

block_cipher = None

import subprocess
import datetime

commit = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).strip().decode('utf-8')
builddate = datetime.datetime.now().strftime('%Y%m%d')

with open('luftdatentool/_buildid.py', 'w') as fd:
    fd.write('''# This file is autogenerated in luftdaten-tool.spec file
commit = "{commit}"
builddate = "{builddate}"'''.format(commit=commit, builddate=builddate))

a = Analysis(['luftdaten-tool.py'],
             pathex=['.'],
             binaries=[],
             datas=[('assets/', './assets'), ('i18n/*.qm', './i18n')],
             hiddenimports=['PyQt5.sip'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='luftdaten-tool',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False,
          icon='assets/logo.ico')

# This is used on MacOS only
app = BUNDLE(exe,
             name='Luftdaten.info Flashing Tool.app',
             icon='assets/logo.icns',
             bundle_identifier=None)
