# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.globalMessage = QtWidgets.QFrame(self.centralwidget)
        self.globalMessage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.globalMessage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.globalMessage.setObjectName("globalMessage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.globalMessage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.globalMessageTitle = QtWidgets.QLabel(self.globalMessage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.globalMessageTitle.setFont(font)
        self.globalMessageTitle.setText("")
        self.globalMessageTitle.setObjectName("globalMessageTitle")
        self.verticalLayout_2.addWidget(self.globalMessageTitle)
        self.globalMessageText = QtWidgets.QLabel(self.globalMessage)
        self.globalMessageText.setText("")
        self.globalMessageText.setOpenExternalLinks(True)
        self.globalMessageText.setObjectName("globalMessageText")
        self.verticalLayout_2.addWidget(self.globalMessageText)
        self.verticalLayout.addWidget(self.globalMessage)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.programmingTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programmingTab.sizePolicy().hasHeightForWidth())
        self.programmingTab.setSizePolicy(sizePolicy)
        self.programmingTab.setObjectName("programmingTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.programmingTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_eraseText = QtWidgets.QLabel(self.programmingTab)
        self.label_eraseText.setTextFormat(QtCore.Qt.RichText)
        self.label_eraseText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_eraseText.setWordWrap(True)
        self.label_eraseText.setObjectName("label_eraseText")
        self.gridLayout_2.addWidget(self.label_eraseText, 0, 0, 1, 1)
        self.label_board = QtWidgets.QLabel(self.programmingTab)
        self.label_board.setObjectName("label_board")
        self.gridLayout_2.addWidget(self.label_board, 1, 0, 1, 1)
        self.boardBox = QtWidgets.QComboBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardBox.sizePolicy().hasHeightForWidth())
        self.boardBox.setSizePolicy(sizePolicy)
        self.boardBox.setObjectName("boardBox")
        self.gridLayout_2.addWidget(self.boardBox, 1, 1, 1, 1)
        self.label_fwVersion = QtWidgets.QLabel(self.programmingTab)
        self.label_fwVersion.setObjectName("label_fwVersion")
        self.gridLayout_2.addWidget(self.label_fwVersion, 2, 0, 1, 1)
        self.versionBox = QtWidgets.QComboBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionBox.sizePolicy().hasHeightForWidth())
        self.versionBox.setSizePolicy(sizePolicy)
        self.versionBox.setEditable(True)
        self.versionBox.setObjectName("versionBox")
        self.gridLayout_2.addWidget(self.versionBox, 2, 1, 1, 1)
        self.label_spacer = QtWidgets.QLabel(self.programmingTab)
        self.label_spacer.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer.setWordWrap(True)
        self.label_spacer.setObjectName("label_spacer")
        self.gridLayout_2.addWidget(self.label_spacer, 3, 0, 1, 2)
        self.label_progress = QtWidgets.QLabel(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_progress.sizePolicy().hasHeightForWidth())
        self.label_progress.setSizePolicy(sizePolicy)
        self.label_progress.setObjectName("label_progress")
        self.gridLayout_2.addWidget(self.label_progress, 4, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.programmingTab)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 5, 0, 1, 2)
        self.label_spacer1 = QtWidgets.QLabel(self.programmingTab)
        self.label_spacer1.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer1.setWordWrap(True)
        self.label_spacer1.setObjectName("label_spacer1")
        self.gridLayout_2.addWidget(self.label_spacer1, 6, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uploadButton = QtWidgets.QPushButton(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadButton.sizePolicy().hasHeightForWidth())
        self.uploadButton.setSizePolicy(sizePolicy)
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout.addWidget(self.uploadButton)
        self.expertModeBox = QtWidgets.QCheckBox(self.programmingTab)
        self.expertModeBox.setCheckable(True)
        self.expertModeBox.setObjectName("expertModeBox")
        self.horizontalLayout.addWidget(self.expertModeBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 7, 0, 1, 2)
        self.label_spacer2 = QtWidgets.QLabel(self.programmingTab)
        self.label_spacer2.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer2.setWordWrap(True)
        self.label_spacer2.setObjectName("label_spacer2")
        self.gridLayout_2.addWidget(self.label_spacer2, 8, 0, 1, 2)
        self.label_eraseText1 = QtWidgets.QLabel(self.programmingTab)
        self.label_eraseText1.setTextFormat(QtCore.Qt.RichText)
        self.label_eraseText1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_eraseText1.setWordWrap(True)
        self.label_eraseText1.setObjectName("label_eraseText1")
        self.gridLayout_2.addWidget(self.label_eraseText1, 9, 0, 1, 1)
        self.label_eraseText2 = QtWidgets.QLabel(self.programmingTab)
        self.label_eraseText2.setTextFormat(QtCore.Qt.RichText)
        self.label_eraseText2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_eraseText2.setWordWrap(True)
        self.label_eraseText2.setObjectName("label_eraseText2")
        self.gridLayout_2.addWidget(self.label_eraseText2, 9, 1, 1, 1)
        self.label_SDS011 = QtWidgets.QLabel(self.programmingTab)
        self.label_SDS011.setObjectName("label_SDS011")
        self.gridLayout_2.addWidget(self.label_SDS011, 10, 0, 1, 1)
        self.check_SDS011 = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.check_SDS011.sizePolicy().hasHeightForWidth())
        self.check_SDS011.setSizePolicy(sizePolicy)
        self.check_SDS011.setObjectName("check_SDS011")
        self.gridLayout_2.addWidget(self.check_SDS011, 10, 1, 1, 1)
        self.label_DHT22 = QtWidgets.QLabel(self.programmingTab)
        self.label_DHT22.setObjectName("label_DHT22")
        self.gridLayout_2.addWidget(self.label_DHT22, 11, 0, 1, 1)
        self.check_DHT22 = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_DHT22.sizePolicy().hasHeightForWidth())
        self.check_DHT22.setSizePolicy(sizePolicy)
        self.check_DHT22.setObjectName("check_DHT22")
        self.gridLayout_2.addWidget(self.check_DHT22, 11, 1, 1, 1)
        self.label_PPD42 = QtWidgets.QLabel(self.programmingTab)
        self.label_PPD42.setObjectName("label_PPD42")
        self.gridLayout_2.addWidget(self.label_PPD42, 12, 0, 1, 1)
        self.check_PPD42 = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_PPD42.sizePolicy().hasHeightForWidth())
        self.check_PPD42.setSizePolicy(sizePolicy)
        self.check_PPD42.setObjectName("check_PPD42")
        self.gridLayout_2.addWidget(self.check_PPD42, 12, 1, 1, 1)
        self.label_PMSx003 = QtWidgets.QLabel(self.programmingTab)
        self.label_PMSx003.setObjectName("label_PMSx003")
        self.gridLayout_2.addWidget(self.label_PMSx003, 13, 0, 1, 1)
        self.check_PMSx003 = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_PMSx003.sizePolicy().hasHeightForWidth())
        self.check_PMSx003.setSizePolicy(sizePolicy)
        self.check_PMSx003.setObjectName("check_PMSx003")
        self.gridLayout_2.addWidget(self.check_PMSx003, 13, 1, 1, 1)
        self.label_SPS30 = QtWidgets.QLabel(self.programmingTab)
        self.label_SPS30.setObjectName("label_SPS30")
        self.gridLayout_2.addWidget(self.label_SPS30, 14, 0, 1, 1)
        self.check_SPS30 = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_SPS30.sizePolicy().hasHeightForWidth())
        self.check_SPS30.setSizePolicy(sizePolicy)
        self.check_SPS30.setObjectName("check_SPS30")
        self.gridLayout_2.addWidget(self.check_SPS30, 14, 1, 1, 1)
        self.label_BMP = QtWidgets.QLabel(self.programmingTab)
        self.label_BMP.setObjectName("label_BMP")
        self.gridLayout_2.addWidget(self.label_BMP, 15, 0, 1, 1)
        self.check_BMP = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_BMP.sizePolicy().hasHeightForWidth())
        self.check_BMP.setSizePolicy(sizePolicy)
        self.check_BMP.setObjectName("check_BMP")
        self.gridLayout_2.addWidget(self.check_BMP, 15, 1, 1, 1)
        self.label_BME280 = QtWidgets.QLabel(self.programmingTab)
        self.label_BME280.setObjectName("label_BME280")
        self.gridLayout_2.addWidget(self.label_BME280, 16, 0, 1, 1)
        self.check_BME280 = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_BME280.sizePolicy().hasHeightForWidth())
        self.check_BME280.setSizePolicy(sizePolicy)
        self.check_BME280.setObjectName("check_BME280")
        self.gridLayout_2.addWidget(self.check_BME280, 16, 1, 1, 1)
        self.label_SHT3X = QtWidgets.QLabel(self.programmingTab)
        self.label_SHT3X.setObjectName("label_SHT3X")
        self.gridLayout_2.addWidget(self.label_SHT3X, 17, 0, 1, 1)
        self.check_SHT3X = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_SHT3X.sizePolicy().hasHeightForWidth())
        self.check_SHT3X.setSizePolicy(sizePolicy)
        self.check_SHT3X.setObjectName("check_SHT3X")
        self.gridLayout_2.addWidget(self.check_SHT3X, 17, 1, 1, 1)
        self.label_HTU21D = QtWidgets.QLabel(self.programmingTab)
        self.label_HTU21D.setObjectName("label_HTU21D")
        self.gridLayout_2.addWidget(self.label_HTU21D, 18, 0, 1, 1)
        self.check_HTU21D = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_HTU21D.sizePolicy().hasHeightForWidth())
        self.check_HTU21D.setSizePolicy(sizePolicy)
        self.check_HTU21D.setObjectName("check_HTU21D")
        self.gridLayout_2.addWidget(self.check_HTU21D, 18, 1, 1, 1)
        self.label_Geiger_Counter = QtWidgets.QLabel(self.programmingTab)
        self.label_Geiger_Counter.setObjectName("label_Geiger_Counter")
        self.gridLayout_2.addWidget(self.label_Geiger_Counter, 19, 0, 1, 1)
        self.check_Geiger_Counter = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_Geiger_Counter.sizePolicy().hasHeightForWidth())
        self.check_Geiger_Counter.setSizePolicy(sizePolicy)
        self.check_Geiger_Counter.setObjectName("check_Geiger_Counter")
        self.gridLayout_2.addWidget(self.check_Geiger_Counter, 19, 1, 1, 1)
        self.label_CCS811 = QtWidgets.QLabel(self.programmingTab)
        self.label_CCS811.setObjectName("label_CCS811")
        self.gridLayout_2.addWidget(self.label_CCS811, 20, 0, 1, 1)
        self.check_CCS811 = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_CCS811.sizePolicy().hasHeightForWidth())
        self.check_CCS811.setSizePolicy(sizePolicy)
        self.check_CCS811.setObjectName("check_CCS811")
        self.gridLayout_2.addWidget(self.check_CCS811, 20, 1, 1, 1)
        self.label_CCS811_5B = QtWidgets.QLabel(self.programmingTab)
        self.label_CCS811_5B.setObjectName("label_CCS811_5B")
        self.gridLayout_2.addWidget(self.label_CCS811_5B, 21, 0, 1, 1)
        self.check_CCS811_5B = QtWidgets.QCheckBox(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_CCS811_5B.sizePolicy().hasHeightForWidth())
        self.check_CCS811_5B.setSizePolicy(sizePolicy)
        self.check_CCS811_5B.setObjectName("check_CCS811_5B")
        self.gridLayout_2.addWidget(self.check_CCS811_5B, 21, 1, 1, 1)
        self.label_DonatedBy = QtWidgets.QLabel(self.programmingTab)
        self.label_DonatedBy.setObjectName("label_DonatedBy")
        self.gridLayout_2.addWidget(self.label_DonatedBy, 22, 0, 1, 1)
        self.DonatedBy = QtWidgets.QLineEdit(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DonatedBy.sizePolicy().hasHeightForWidth())
        self.DonatedBy.setSizePolicy(sizePolicy)
        self.DonatedBy.setObjectName("DonatedBy")
        self.gridLayout_2.addWidget(self.DonatedBy, 22, 1, 1, 1)
        self.label_spacer3 = QtWidgets.QLabel(self.programmingTab)
        self.label_spacer3.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer3.setWordWrap(True)
        self.label_spacer3.setObjectName("label_spacer3")
        self.gridLayout_2.addWidget(self.label_spacer3, 23, 0, 1, 2)
        self.label_progress_config = QtWidgets.QLabel(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_progress_config.sizePolicy().hasHeightForWidth())
        self.label_progress_config.setSizePolicy(sizePolicy)
        self.label_progress_config.setObjectName("label_progress_config")
        self.gridLayout_2.addWidget(self.label_progress_config, 24, 0, 1, 2)
        self.progressBar_config = QtWidgets.QProgressBar(self.programmingTab)
        self.progressBar_config.setObjectName("progressBar_config")
        self.gridLayout_2.addWidget(self.progressBar_config, 25, 0, 1, 2)
        self.label_spacer4 = QtWidgets.QLabel(self.programmingTab)
        self.label_spacer4.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer4.setWordWrap(True)
        self.label_spacer4.setObjectName("label_spacer4")
        self.gridLayout_2.addWidget(self.label_spacer4, 26, 0, 1, 2)
        self.wifiButton = QtWidgets.QPushButton(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wifiButton.sizePolicy().hasHeightForWidth())
        self.wifiButton.setSizePolicy(sizePolicy)
        self.wifiButton.setObjectName("wifiButton")
        self.gridLayout_2.addWidget(self.wifiButton, 27, 0, 1, 2)
        self.expertForm = QtWidgets.QWidget(self.programmingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expertForm.sizePolicy().hasHeightForWidth())
        self.expertForm.setSizePolicy(sizePolicy)
        self.expertForm.setObjectName("expertForm")
        self.formLayout_2 = QtWidgets.QFormLayout(self.expertForm)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.expertForm)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.expertForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.textBrowser = QtWidgets.QTextBrowser(self.expertForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.textBrowser)
        self.gridLayout_2.addWidget(self.expertForm, 9, 0, 1, 2)
        self.gridLayout_2.setRowStretch(8, 1)
        self.tabWidget.addTab(self.programmingTab, "")
        self.configTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configTab.sizePolicy().hasHeightForWidth())
        self.configTab.setSizePolicy(sizePolicy)
        self.configTab.setObjectName("configTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.configTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_customName = QtWidgets.QLabel(self.configTab)
        self.label_customName.setObjectName("label_customName")
        self.gridLayout_5.addWidget(self.label_customName, 0, 0, 1, 1)
        self.customName = QtWidgets.QLineEdit(self.configTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customName.sizePolicy().hasHeightForWidth())
        self.customName.setSizePolicy(sizePolicy)
        self.customName.setObjectName("customName")
        self.gridLayout_5.addWidget(self.customName, 0, 1, 1, 1)
        self.label_empty_field = QtWidgets.QLabel(self.configTab)
        self.label_empty_field.setObjectName("label_empty_field")
        self.gridLayout_5.addWidget(self.label_empty_field, 1, 0, 1, 1)
        self.label_desc_empty_password = QtWidgets.QLabel(self.configTab)
        self.label_desc_empty_password.setObjectName("label_desc_empty_password")
        self.gridLayout_5.addWidget(self.label_desc_empty_password, 1, 1, 1, 1)
        self.label_sensor1 = QtWidgets.QLabel(self.configTab)
        self.label_sensor1.setObjectName("label_sensor1")
        self.gridLayout_5.addWidget(self.label_sensor1, 3, 0, 1, 1)
        self.sensor1Box = QtWidgets.QComboBox(self.configTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor1Box.sizePolicy().hasHeightForWidth())
        self.sensor1Box.setSizePolicy(sizePolicy)
        self.sensor1Box.setEditable(True)
        self.sensor1Box.setObjectName("sensor1Box")
        self.gridLayout_5.addWidget(self.sensor1Box, 3, 1, 1, 1)
        self.label_sensor2 = QtWidgets.QLabel(self.configTab)
        self.label_sensor2.setObjectName("label_sensor2")
        self.gridLayout_5.addWidget(self.label_sensor2, 4, 0, 1, 1)
        self.sensor2Box = QtWidgets.QComboBox(self.configTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor2Box.sizePolicy().hasHeightForWidth())
        self.sensor2Box.setSizePolicy(sizePolicy)
        self.sensor2Box.setEditable(True)
        self.sensor2Box.setObjectName("sensor2Box")
        self.gridLayout_5.addWidget(self.sensor2Box, 4, 1, 1, 1)
        self.label_DonatedBy1 = QtWidgets.QLabel(self.configTab)
        self.label_DonatedBy1.setObjectName("label_DonatedBy1")
        self.gridLayout_5.addWidget(self.label_DonatedBy1, 5, 0, 1, 1)
        self.DonatedBy1 = QtWidgets.QLineEdit(self.configTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DonatedBy1.sizePolicy().hasHeightForWidth())
        self.DonatedBy1.setSizePolicy(sizePolicy)
        self.DonatedBy1.setObjectName("DonatedBy1")
        self.gridLayout_5.addWidget(self.DonatedBy1, 5, 1, 1, 1)
        self.label_empty_field1 = QtWidgets.QLabel(self.configTab)
        self.label_empty_field1.setObjectName("label_empty_field1")
        self.gridLayout_5.addWidget(self.label_empty_field1, 6, 0, 1, 1)
        self.label_desc_empty_password1 = QtWidgets.QLabel(self.configTab)
        self.label_desc_empty_password1.setObjectName("label_desc_empty_password1")
        self.gridLayout_5.addWidget(self.label_desc_empty_password1, 6, 1, 1, 1)
        self.label_spacer5 = QtWidgets.QLabel(self.configTab)
        self.label_spacer5.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer5.setWordWrap(True)
        self.label_spacer5.setObjectName("label_spacer5")
        self.gridLayout_5.addWidget(self.label_spacer5, 8, 0, 1, 2)
        self.label_progress_config1 = QtWidgets.QLabel(self.configTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_progress_config1.sizePolicy().hasHeightForWidth())
        self.label_progress_config1.setSizePolicy(sizePolicy)
        self.label_progress_config1.setObjectName("label_progress_config1")
        self.gridLayout_5.addWidget(self.label_progress_config1, 9, 0, 1, 2)
        self.progressBar_config1 = QtWidgets.QProgressBar(self.configTab)
        self.progressBar_config1.setObjectName("progressBar_config1")
        self.gridLayout_5.addWidget(self.progressBar_config1, 10, 0, 1, 2)
        self.label_spacer6 = QtWidgets.QLabel(self.configTab)
        self.label_spacer6.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer6.setWordWrap(True)
        self.label_spacer6.setObjectName("label_spacer6")
        self.gridLayout_5.addWidget(self.label_spacer6, 11, 0, 1, 2)
        self.wifiButton1 = QtWidgets.QPushButton(self.configTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wifiButton1.sizePolicy().hasHeightForWidth())
        self.wifiButton1.setSizePolicy(sizePolicy)
        self.wifiButton1.setObjectName("wifiButton1")
        self.gridLayout_5.addWidget(self.wifiButton1, 12, 0, 1, 2)
        self.gridLayout_5.setRowStretch(14, 1)
        self.tabWidget.addTab(self.configTab, "")
        self.resetTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetTab.sizePolicy().hasHeightForWidth())
        self.resetTab.setSizePolicy(sizePolicy)
        self.resetTab.setObjectName("resetTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.resetTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_eraseText3 = QtWidgets.QLabel(self.resetTab)
        self.label_eraseText3.setTextFormat(QtCore.Qt.RichText)
        self.label_eraseText3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_eraseText3.setWordWrap(True)
        self.label_eraseText3.setObjectName("label_eraseText3")
        self.gridLayout_6.addWidget(self.label_eraseText3, 0, 0, 1, 1)
        self.label_spacer7 = QtWidgets.QLabel(self.resetTab)
        self.label_spacer7.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer7.setWordWrap(True)
        self.label_spacer7.setObjectName("label_spacer7")
        self.gridLayout_6.addWidget(self.label_spacer7, 1, 0, 1, 2)
        self.label_progress1 = QtWidgets.QLabel(self.resetTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_progress1.sizePolicy().hasHeightForWidth())
        self.label_progress1.setSizePolicy(sizePolicy)
        self.label_progress1.setObjectName("label_progress1")
        self.gridLayout_6.addWidget(self.label_progress1, 2, 0, 1, 1)
        self.progressBar_erase = QtWidgets.QProgressBar(self.resetTab)
        self.progressBar_erase.setObjectName("progressBar_erase")
        self.gridLayout_6.addWidget(self.progressBar_erase, 3, 0, 1, 2)
        self.label_spacer8 = QtWidgets.QLabel(self.resetTab)
        self.label_spacer8.setTextFormat(QtCore.Qt.RichText)
        self.label_spacer8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_spacer8.setWordWrap(True)
        self.label_spacer8.setObjectName("label_spacer8")
        self.gridLayout_6.addWidget(self.label_spacer8, 4, 0, 1, 2)
        self.eraseButton = QtWidgets.QPushButton(self.resetTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eraseButton.sizePolicy().hasHeightForWidth())
        self.eraseButton.setSizePolicy(sizePolicy)
        self.eraseButton.setObjectName("eraseButton")
        self.gridLayout_6.addWidget(self.eraseButton)
        self.gridLayout_6.setRowStretch(7, 1)
        self.tabWidget.addTab(self.resetTab, "")
        self.discoveryTab = QtWidgets.QWidget()
        self.discoveryTab.setObjectName("discoveryTab")
        self.gridLayout = QtWidgets.QGridLayout(self.discoveryTab)
        self.gridLayout.setObjectName("gridLayout")
        self.discoveryList = QtWidgets.QListWidget(self.discoveryTab)
        self.discoveryList.setObjectName("discoveryList")
        self.gridLayout.addWidget(self.discoveryList, 3, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.discoveryTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.discoveryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.discoveryRefreshButton = QtWidgets.QPushButton(self.discoveryTab)
        self.discoveryRefreshButton.setObjectName("discoveryRefreshButton")
        self.gridLayout.addWidget(self.discoveryRefreshButton, 1, 1, 1, 1)
        self.tabWidget.addTab(self.discoveryTab, "")
        self.serialTab = QtWidgets.QWidget()
        self.serialTab.setObjectName("serialTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.serialTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.serialTextEdit = QtWidgets.QTextEdit(self.serialTab)
        self.serialTextEdit.setObjectName("serialTextEdit")
        self.gridLayout_4.addWidget(self.serialTextEdit, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.serialTab)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.serialConnectButton = QtWidgets.QPushButton(self.serialTab)
        self.serialConnectButton.setCheckable(True)
        self.serialConnectButton.setObjectName("serialConnectButton")
        self.gridLayout_4.addWidget(self.serialConnectButton, 1, 0, 1, 1)
        self.tabWidget.addTab(self.serialTab, "")
        self.aboutTab = QtWidgets.QWidget()
        self.aboutTab.setObjectName("aboutTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.aboutTab)
        self.gridLayout_3.setSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buildLabel = QtWidgets.QLabel(self.aboutTab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.buildLabel.setFont(font)
        self.buildLabel.setObjectName("buildLabel")
        self.gridLayout_3.addWidget(self.buildLabel, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.aboutTab)
        self.label_6.setMaximumSize(QtCore.QSize(64, 64))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../assets/logo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.aboutTab)
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setWordWrap(True)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 2)
        self.tabWidget.addTab(self.aboutTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensor.Community - Airrohr Flasher (v{version})"))
        self.label_eraseText.setText(_translate("MainWindow", "<b>Flash Firmware</b>"))
        self.label_board.setText(_translate("MainWindow", "Board:"))
        self.label_fwVersion.setText(_translate("MainWindow", "Firmware version:"))
        self.label_spacer.setText(_translate("MainWindow", " "))
        self.label_progress.setText(_translate("MainWindow", "Progress:"))
        self.label_spacer1.setText(_translate("MainWindow", " "))
        self.uploadButton.setText(_translate("MainWindow", "Upload"))
        self.expertModeBox.setText(_translate("MainWindow", "Expert mode"))
        self.label_spacer2.setText(_translate("MainWindow", " "))
        self.label_eraseText1.setText(_translate("MainWindow", "<b>Configure</b>"))
        self.label_eraseText2.setText(_translate("MainWindow", "<b>(Reconnect ESP before saving configuration!)</b>"))
        self.label_SDS011.setText(_translate("MainWindow", "SDS011"))
        self.label_DHT22.setText(_translate("MainWindow", "DHT22"))
        self.label_PPD42.setText(_translate("MainWindow", "PPD42"))
        self.label_PMSx003.setText(_translate("MainWindow", "PMSx003"))
        self.label_SPS30.setText(_translate("MainWindow", "SPS30"))
        self.label_BMP.setText(_translate("MainWindow", "BMP"))
        self.label_BME280.setText(_translate("MainWindow", "BME280"))
        self.label_SHT3X.setText(_translate("MainWindow", "SHT3X"))
        self.label_HTU21D.setText(_translate("MainWindow", "HTU21D"))
        self.label_Geiger_Counter.setText(_translate("MainWindow", "Geiger Counter"))
        self.label_CCS811.setText(_translate("MainWindow", "CCS811"))
        self.label_CCS811_5B.setText(_translate("MainWindow", "CCS811_5B"))
        self.label_DonatedBy.setText(_translate("MainWindow", "Donated by:"))
        self.label_spacer3.setText(_translate("MainWindow", " "))
        self.label_progress_config.setText(_translate("MainWindow", "Progress:"))
        self.label_spacer4.setText(_translate("MainWindow", " "))
        self.wifiButton.setText(_translate("MainWindow", "Save configuration"))
        self.label_3.setText(_translate("MainWindow", "Baudrate:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.programmingTab), _translate("MainWindow", "Flashing"))
        self.label_customName.setText(_translate("MainWindow", "Custom name:"))
        self.label_empty_field.setText(_translate("MainWindow", " "))
        self.label_desc_empty_password.setText(_translate("MainWindow", "(Change only if really needed.)"))
        self.label_sensor1.setText(_translate("MainWindow", "Sensor 1:"))
        self.label_sensor2.setText(_translate("MainWindow", "Sensor 2:"))
        self.label_DonatedBy1.setText(_translate("MainWindow", "Donated by:"))
        self.label_empty_field1.setText(_translate("MainWindow", " "))
        self.label_desc_empty_password1.setText(_translate("MainWindow", "(Check \"empty\" if you want to use the device in a wifi network without password.)"))
        self.label_spacer5.setText(_translate("MainWindow", " "))
        self.label_progress_config1.setText(_translate("MainWindow", "Progress:"))
        self.label_spacer6.setText(_translate("MainWindow", " "))
        self.wifiButton1.setText(_translate("MainWindow", "Save configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), _translate("MainWindow", "Configure"))
        self.label_eraseText3.setText(_translate("MainWindow", "This will completely erase the flash memory (firmware and configuration). After that you will need to reflash the firmware and reconfigure the device."))
        self.label_spacer7.setText(_translate("MainWindow", " "))
        self.label_progress1.setText(_translate("MainWindow", " "))
        self.label_spacer8.setText(_translate("MainWindow", " "))
        self.eraseButton.setText(_translate("MainWindow", "Erase Flash"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resetTab), _translate("MainWindow", "Erase flash"))
        self.label_5.setText(_translate("MainWindow", "Double-click to open configuration page."))
        self.label_4.setText(_translate("MainWindow", "Sensors detected in local network:"))
        self.discoveryRefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.discoveryTab), _translate("MainWindow", "Discovery"))
        self.label_9.setText(_translate("MainWindow", "In case of sensor issues, Serial Monitor can be used to review logs sent by the sensor over USB cable."))
        self.serialConnectButton.setText(_translate("MainWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.serialTab), _translate("MainWindow", "Serial Monitor"))
        self.buildLabel.setText(_translate("MainWindow", "<b>Sensor.Community Airrohr Flasher</b><br/>Build {build_id}"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Original version developed by <a href=\"https://inf.re/\"><span style=\" text-decoration: underline; color:#0000ff;\">Piotr Dobrowolski</span></a>.</p><p>This software is released under the terms of MIT license. No warranty is provided.</p><p>For newest release see: <a href=\"https://firmware.sensor.community/airrohr/flashing-tool/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/LoSk-p/airrohr-firmware-flasher/releases/</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutTab), _translate("MainWindow", "About"))

